=== Kyllian-chr/Tux/TUX/Data/xsd/profil.xsd
<?xml version="1.0"?>
<xs:schema version="1.0"
           targetNamespace="http://myGame/tux"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:tux="http://myGame/tux"
           elementFormDefault="qualified">

    <xs:include schemaLocation="dico.xsd"/>
    
    <!-- Racine du shema : profil-->
    <xs:element name="profil" type="tux:Profil"/>
    
    <!-- Composition d'un Profil-->
    <xs:complexType name="Profil">
        <xs:sequence>
            <xs:element name="nom" type="xs:string"/>
            <xs:element name="avatar" type="xs:string"/>
            <xs:element name="anniversaire" type="xs:date"/>
            <xs:element name="parties" type="tux:Parties"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="Parties">
        <xs:sequence>
            <xs:element name="partie" type="tux:Partie" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="Partie">
        <xs:sequence>
            <xs:element name="temps" minOccurs="0" type="xs:double"/>
            <xs:element name="niveau" type="tux:Niveau"/>
        </xs:sequence>
        <xs:attribute name="trouve" type="xs:string"/>
        <xs:attribute name="date" type="xs:date"/>
    </xs:complexType>

    
    
</xs:schema>

=== Kyllian-chr/Tux/TUX/Data/xml/profil.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--
    Document   : save_example.xml.xml
    Created on : August 31, 2014, 3:31 PM
    Author     : Johan Sarrazin / CÃ©line Fouard / Nicolas Glade
    Description:
        Purpose of the document follows.
-->

<!--Joueur 1-->
<ns1:profil xmlns:ns1="http://myGame/tux" 
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:schemaLocation="http://myGame/tux ../xsd/profil.xsd">
        
    
        <ns1:nom>Alban</ns1:nom>
        <ns1:avatar>conan.jpg</ns1:avatar>
        <ns1:anniversaire>2006-05-08</ns1:anniversaire>
        <ns1:parties>
            <ns1:partie date="2013-12-10">
                <ns1:temps>20.0</ns1:temps>
                <ns1:niveau difficulte="1">
                    <ns1:mot>Cle</ns1:mot>   
                </ns1:niveau>
            </ns1:partie>
            <ns1:partie trouve="75%" date="2013-12-11">
                <ns1:niveau difficulte="2">
                    <ns1:mot>Indice</ns1:mot>   
                </ns1:niveau>
            </ns1:partie>
            <ns1:partie date="2013-12-11">
                <ns1:temps>20.0</ns1:temps>
                <ns1:niveau difficulte="2">
                    <ns1:mot>Indice</ns1:mot>   
                </ns1:niveau>
            </ns1:partie>
        </ns1:parties>
    
    
</ns1:profil>

=== Kyllian-chr/Tux/TUX/Data/xml/profil2.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<!--
    Document   : save_example.xml.xml
    Created on : August 31, 2014, 3:31 PM
    Author     : Johan Sarrazin / CÃ©line Fouard / Nicolas Glade
    Description:
        Purpose of the document follows.
-->

<!--Joueur 2-->
<ns1:profil xmlns:ns1="http://myGame/tux" 
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:schemaLocation="http://myGame/tux ../xsd/profil.xsd">
    
    
        <ns1:nom>PapeauLeGuerrrrrrier</ns1:nom>
        <ns1:avatar>barbare.png</ns1:avatar>
        <ns1:anniversaire>2009-10-01</ns1:anniversaire>
        <ns1:parties>
            <ns1:partie date="2015-09-04">
                <ns1:temps>25.1</ns1:temps>
                <ns1:niveau difficulte="1">
                    <ns1:mot>Non</ns1:mot>   
                </ns1:niveau>
            </ns1:partie>
            <ns1:partie date="2013-12-11" trouve="25%">
                <ns1:niveau difficulte="2">
                    <ns1:mot>Manger</ns1:mot>   
                </ns1:niveau>
            </ns1:partie>
            <ns1:partie date="2013-12-11">
                <ns1:temps>20.0</ns1:temps>
                <ns1:niveau difficulte="2">
                    <ns1:mot>Pratiquer</ns1:mot>   
                </ns1:niveau>
            </ns1:partie>
        </ns1:parties>  
    
    
</ns1:profil>
